export const LIMITED_COUNTRIES = [
    "Russia",
    "Tajikistan",
    "Laos",
    "Bhutan",
    "Virgin Islands (U.S.)",
    "South Korea",
    "Argentina",
    "Bulgaria",
    "Algeria",
    "Burkina Faso",
    "Côte D'Ivoire",
    "Belgium",
    "Ethiopia",
    "Lithuania",
    "Congo",
    "Eswatini",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Mayotte",
    "Sweden",
    "Lesotho",
    "Mali",
    "French Guiana",
    "Guinea Bissau",
    "Guyana",
    "Djibouti",
    "Guatemala",
    "Rwanda",
    "Bosnia And Herzegovina",
    "Dominican Republic",
    "Austria",
    "El Salvador",
    "Bahamas",
    "Tonga",
    "Kiribati",
    "Kuwait",
    "Guam",
    "Palau",
    "Saint Lucia",
    "Sint Maarten (Dutch part)",
    "Curaçao",
    "Saint Vincent and the Grenadines",
    "Papua New Guinea",
    "Nepal",
    "Maldives",
    "Panama",
    "Chad",
    "Nauru",
    "Bolivia",
    "Ghana",
    "Estonia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Mauritius",
    "Sao Tome and Principe",
    "Gambia",
    "Suriname",
    "Libya",
    "Western Sahara",
    "Italy",
    "France",
    "Nicaragua",
    "Cayman Islands",
    "Saudi Arabia",
    "Qatar",
    "Bahrain",
    "Saint Kitts and Nevis",
    "Sri Lanka",
    "Virgin Islands (British)",
    "Myanmar",
    "Malaysia",
    "Malawi",
    "Christmas Island",
    "South Africa",
    "Colombia",
    "Niger",
    "Guernsey",
    "Jersey",
    "Latvia",
    "Botswana",
    "Tanzania",
    "South Sudan",
    "Croatia",
    "Saint Pierre and Miquelon",
    "Romania",
    "Turkey",
    "Gibraltar",
    "Niue",
    "Cook Islands",
    "Puerto Rico",
    "Uruguay",
    "Barbados",
    "Guadeloupe",
    "Aruba",
    "Bonaire, Sint Eustatius and Saba",
    "Montserrat",
    "Kyrgyzstan",
    "United States",
    "Venezuela",
    "Australia",
    "Yemen",
    "Cocos (Keeling) Islands",
    "China",
    "Mexico",
    "Iceland",
    "Togo",
    "Isle of Man",
    "Netherlands",
    "Denmark",
    "Germany",
    "Central African Republic",
    "Fiji",
    "Micronesia (Federated States of)",
    "Liberia",
    "Equatorial Guinea",
    "Namibia",
    "Spain",
    "Guinea",
    "Burundi",
    "Morocco",
    "Albania",
    "Malta",
    "Portugal",
    "Moldova",
    "Turks and Caicos Islands",
    "Belize",
    "Vanuatu",
    "New Caledonia",
    "Trinidad and Tobago",
    "Armenia",
    "Belarus",
    "Uzbekistan",
    "India",
    "Bangladesh",
    "Thailand",
    "Singapore",
    "Mongolia",
    "Somalia",
    "Marshall Islands",
    "Greenland",
    "Kenya",
    "Egypt",
    "Ireland",
    "Poland",
    "Réunion",
    "Congo (Democratic Republic Of The)",
    "Zimbabwe",
    "Senegal",
    "Cabo Verde",
    "Cyprus",
    "Macedonia",
    "Montenegro",
    "Slovenia",
    "Switzerland",
    "Saint Martin (French part)",
    "Haiti",
    "Iran",
    "Pakistan",
    "Iraq",
    "Syria",
    "Northern Mariana Islands",
    "Japan",
    "Dominica",
    "Grenada",
    "Ukraine",
    "Indonesia",
    "Canada",
    "Philippines",
    "Norfolk Island",
    "Sudan",
    "Angola",
    "Benin",
    "Cameroon",
    "Comoros",
    "Seychelles",
    "Mauritania",
    "Serbia",
    "Cuba",
    "Tuvalu",
    "American Samoa",
    "Samoa",
    "New Zealand",
    "Martinique",
    "Anguilla",
    "Bermuda",
    "Cambodia",
    "Hong Kong",
    "Mozambique",
    "Brunei Darussalam",
    "Zambia",
    "Nigeria",
    "Tunisia",
    "Finland",
    "Gabon",
    "Sierra Leone",
    "Eritrea",
    "Greece",
    "Czech Republic",
    "Israel",
    "Jamaica",
    "Afghanistan",
    "Jordan",
    "Wallis and Futuna",
    "Chile",
    "Antigua and Barbuda",
    "Azerbaijan",
    "Georgia",
    "Turkmenistan",
    "Paraguay",
    "Macao",
    "Vietnam",
    "Madagascar",
    "Kazakhstan",
    "Timor-Leste",
    "Brazil",
    "United Kingdom",
    "Solomon Islands",
    "United Arab Emirates",
    "Costa Rica",
    "Ecuador",
    "Luxembourg",
    "Norway",
    "Honduras",
    "Uganda",
    "Korea, Republic of",
    "Hungary",
    "Slovakia",
    "French Polynesia",
    "Lebanon",
    "Oman",
    "Peru",
    "Taiwan",
    "Saint Barthélemy"
]